baseURL = "http://example.org/"
languageCode = "en-us"
title = "Ask Cloud Architech"
theme = "hugo-geekdoc"

# Required to get well formatted code blocks
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = false
pluralizeListTitles = false

[params]
    geekdoclogo = "askCloudArchitechLogo.svg"

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9