baseURL = "https://askcloudarchitech.com/"
languageCode = "en-us"
title = "Tips, Tricks and Work Hacks for Software Development Professionals | Ask Cloud Architech"
theme = "hugo-geekdoc"

# Required to get well formatted code blocks
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = false
pluralizeListTitles = false

[params]
    geekdoclogo = "brand.svg"
    geekdocBreadcrumb = true
    geekdocCollapseAllSections = true
    # (Optional, default false) Enable or disable adding tags for post pages automatically to the navigation sidebar.
    geekdocTagsToMenu = true

    # (Optional, default 'title') Configure how to sort file-tree menu entries. Possible options are 'title', 'linktitle',
    # 'date', 'publishdate', 'expirydate' or 'lastmod'. Every option can be used with a reverse modifier as well
    # e.g. 'title_reverse'.
    geekdocFileTreeSortBy = "date"
    geekdocSearchShowParent = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[permalinks]
  common-questions = '/common-questions/'

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'